// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// depth
NumericVector depth(NumericVector f, NumericMatrix fmat);
RcppExport SEXP _extdepth_depth(SEXP fSEXP, SEXP fmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type f(fSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type fmat(fmatSEXP);
    rcpp_result_gen = Rcpp::wrap(depth(f, fmat));
    return rcpp_result_gen;
END_RCPP
}
// extdepth
NumericVector extdepth(NumericVector g, NumericMatrix fmat);
RcppExport SEXP _extdepth_extdepth(SEXP gSEXP, SEXP fmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type g(gSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type fmat(fmatSEXP);
    rcpp_result_gen = Rcpp::wrap(extdepth(g, fmat));
    return rcpp_result_gen;
END_RCPP
}
// extdepth_all
NumericVector extdepth_all(NumericMatrix fmat);
RcppExport SEXP _extdepth_extdepth_all(SEXP fmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type fmat(fmatSEXP);
    rcpp_result_gen = Rcpp::wrap(extdepth_all(fmat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_extdepth_depth", (DL_FUNC) &_extdepth_depth, 2},
    {"_extdepth_extdepth", (DL_FUNC) &_extdepth_extdepth, 2},
    {"_extdepth_extdepth_all", (DL_FUNC) &_extdepth_extdepth_all, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_extdepth(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
