# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
depth_c <- function(f, fmat) {
    .Call('_extdepth_depth_c', PACKAGE = 'extdepth', f, fmat)
}

#' @export
dCDF_c <- function(depths) {
    .Call('_extdepth_dCDF_c', PACKAGE = 'extdepth', depths)
}

#' @export
ED_comparison <- function(f1_cdf, f2_cdf) {
    .Call('_extdepth_ED_comparison', PACKAGE = 'extdepth', f1_cdf, f2_cdf)
}

#' @export
ED_c <- function(fmat) {
    .Call('_extdepth_ED_c', PACKAGE = 'extdepth', fmat)
}

