# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
depth <- function(f, fmat) {
    .Call('_extdepth_depth', PACKAGE = 'extdepth', f, fmat)
}

#' @export
dCDF <- function(depths) {
    .Call('_extdepth_dCDF', PACKAGE = 'extdepth', depths)
}

#' @export
ed_compare <- function(f1_cdf, f2_cdf) {
    .Call('_extdepth_ed_compare', PACKAGE = 'extdepth', f1_cdf, f2_cdf)
}

#' @export
ED <- function(fmat) {
    .Call('_extdepth_ED', PACKAGE = 'extdepth', fmat)
}

#' @export
fast_depth <- function(f, fmat) {
    .Call('_extdepth_fast_depth', PACKAGE = 'extdepth', f, fmat)
}

#' @export
dCDF_r <- function(depths, r) {
    .Call('_extdepth_dCDF_r', PACKAGE = 'extdepth', depths, r)
}

#' @export
fast_ED <- function(fmat) {
    .Call('_extdepth_fast_ED', PACKAGE = 'extdepth', fmat)
}

