# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
depth <- function(f, fmat) {
    .Call('_extdepth_depth', PACKAGE = 'extdepth', f, fmat)
}

#' @export
ED <- function(fmat) {
    .Call('_extdepth_ED', PACKAGE = 'extdepth', fmat)
}

